### ISSUE TITLE
Quote Hash Navigation: Partially blocked by the header

### ISSUE THREAD

**Issue by AlifianK** [TuxedoTako/4chan-xt#10]
It looks like clicking the quote hash in 4chanXT will make the post partially blocked when the header is shown. This is 4chanXT:
![image](https://github.com/TuxedoTako/4chan-xt/assets/50392169/1e3c3538-2ad0-4b8d-b350-e3d6c4a79233)

This is 4chanX:
![image](https://github.com/TuxedoTako/4chan-xt/assets/50392169/35cf2f64-4d0b-4f40-97cc-75899bfeb705)

Note: the 4chanX one is captured on Firefox, and 4chanXT is on Edge.

**Comment by TuxedoTako** [comment]
Like I already said in https://boards.4chan.org/g/thread/97970578#p98000834

> So, I think I found the cause: the code used an old MessageChannel() hack to delay code, to not block the UI. I found it ugly and replaced it with a Promise.resolve().then. The old scroll logic relied on it being called after the browsers build in scroll, and corrected after that. But with the new code, it runs the custom scroll correction first, and then the browser's scroll.

I have to work at my job this week. You can expect a new version with the fix early next week at the latest.

**Comment by saxamaphone69** [comment]
I had previously questioned some alternative ways to do scroll-related code (https://github.com/ccd0/4chan-x/issues/1227 and https://github.com/ccd0/4chan-x/issues/2935). Not sure if that's another avenue that could be taken.

There is also the CSS way to offset it:
```css
.post { scroll-margin-top: 24px; }
```

**Comment by TuxedoTako** [comment]
Can you test 2.2.5?

> There is also the CSS way to offset it:
> 
> ```css
> .post { scroll-margin-top: 24px; }
> ```

Thanks for the suggestion. Using less script for things CSS can do is often better. I did have to replace  `overflow: hidden;`  with  `overflow: clip;` for this to work, so I had to bump the minimum chrome to 90. Let me know if that's a problem.

**Comment by AlifianK** [comment]
Thanks for the release, I can confirm it's fixed.
![image](https://github.com/TuxedoTako/4chan-xt/assets/50392169/0c428a33-c9dc-4325-ac22-e03785e076fd)
