### ISSUE TITLE
[Feature Request] Filter Labels

### ISSUE THREAD

**Issue by saxamaphone69** [TuxedoTako/4chan-xt#108]
A [long-standing](https://github.com/ccd0/4chan-x/issues/126) feature request of ccd0's 4chan X was to include filter labels, as in a reason why a post was triggered by a filter (either highlighting or hiding).

Mayhem had it in his version, but it never made it across.

I had tried (to the best of my ability, which is low) to "port" it over (as mentioned in [this comment](https://github.com/TuxedoTako/4chan-xt/issues/74#issuecomment-2230127885), which links to my original PR attempt and Mayhem's original 2014 commits) but failed.

**Comment by TuxedoTako** [comment]
You can kinda get this since 2.11, which started allowing both highlight and filter, and the stub gets the filter class, so you can do something like:

```
/bait/
/bait/;highlight:bait
```

and then in the custom CSS:

```CSS
.bait .stub::after {
  content: " - bait";
}
```

Which will add that text after the stub: ![msedge_SYOFA8S87G](https://github.com/user-attachments/assets/75d7150a-2e78-47fd-a875-ec4b7179b7dd)

I should update the filters to allow both the highlight and hiding to use one check instead of duplicating it.

**Comment by saxamaphone69** [comment]
I pulled the latest, looking great so far. It looks like I was way off with my attempt...

![image](https://github.com/user-attachments/assets/ce20b03a-c53c-49b0-a1d8-7598b14e7b04)

**Comment by TuxedoTako** [comment]
Released in [2.15.0](https://github.com/TuxedoTako/4chan-xt/releases).

**Comment by saxamaphone69** [comment]
Another big update, thank you Tako!

Can the reason also display for threads, too?

![image](https://github.com/user-attachments/assets/d1e6f48f-19bd-47e4-a4b3-6473f8309e97)

For stubbed threads with a subject, perhaps my [old PR](https://github.com/ccd0/4chan-x/pull/3371/commits/410dc8034dc5a34bd50cf9e96583e7dffd45f69a) could be merged?

Speaking of stubs, the subject (if added), name, and filter reason(s) being wrapped in `span` would allow greater styling options.
```html
<div class="stub">
<a class="show-reply-button" href="javascript:;"><span>➕︎</span> Anonymous (wow what &amp; Filtered comment /from/i)</a><a class="menu-button" href="javascript:;"><svg xmlns="http://www.w3.org/2000/svg" class="icon" viewBox="0 0 320 512"><path d="M137.4 374.6c12.5 12.5 32.8 12.5 45.3 0l128-128c9.2-9.2 11.9-22.9 6.9-34.9s-16.6-19.8-29.6-19.8L32 192c-12.9 0-24.6 7.8-29.6 19.8s-2.2 25.7 6.9 34.9l128 128z" fill="currentColor"></path></svg></a>
</div>
```
into
```html
<div class="stub">
<a class="show-reply-button" href="javascript:;"><span>➕︎</span><span class="stub-subject">/wdg/<span><span class="stub-name">Anonymous</span><span class="stub-reasons">(<span class="stub-reason">wow what</span> &amp; <span class="stub-reason">Filtered comment /from/i</span>)</span></a><a class="menu-button" href="javascript:;"><svg xmlns="http://www.w3.org/2000/svg" class="icon" viewBox="0 0 320 512"><path d="M137.4 374.6c12.5 12.5 32.8 12.5 45.3 0l128-128c9.2-9.2 11.9-22.9 6.9-34.9s-16.6-19.8-29.6-19.8L32 192c-12.9 0-24.6 7.8-29.6 19.8s-2.2 25.7 6.9 34.9l128 128z" fill="currentColor"></path></svg></a>
</div>
```
The brackets and &'s could even be added with CSS instead (something like)
```css
.stub-reasons::before { content: '('; }
.stub-reasons::after { content: ')'; }
.stub-reason:not(:last-of-type or maybe :last-child)::after { content: ' & '; }
```

I guess the other option to support is for reasons to be added to the menu, as opposed to inline or on hover. Perhaps like my poor PR attempt, it is a setting within the Menu section and it could override being displayed inline (off by default). Although, in saying that, if a post is `highlight` instead, the option would have to be in the menu, but only if Menu is enabled

![image](https://github.com/user-attachments/assets/52acd916-fa1b-49ea-b31d-ff72760e7bb0)

I've chucked in a somewhat simple filter: `/we/i;reason:wow what;` and `/from/i;` and it results in a bunch of `undefined` classes:
![image](https://github.com/user-attachments/assets/eee93d76-8b01-40bd-a610-f54fe1972f9a)
the reasons still display:
![image](https://github.com/user-attachments/assets/6e4cfb5e-7716-4a53-ba7a-9f23d21b64b8)

**Comment by TuxedoTako** [comment]
> Can the reason also display for threads, too?

I didn't know thread stubs use different code. It's in 2.15.1.

> For stubbed threads with a subject, perhaps my [old PR](https://github.com/ccd0/4chan-x/pull/3371/commits/410dc8034dc5a34bd50cf9e96583e7dffd45f69a) could be merged?

I recreated it. I can't merge pull requests made against the coffeescript version, because that would just lead to git conflicts.

> Speaking of stubs, the subject (if added), name, and filter reason(s) being wrapped in `span` would allow greater styling options.

> a bunch of `undefined` classes

Also in 2.15.1.

> if a post is `highlight` instead, the option would have to be in the menu,

Do you really need the reason for highlighted posts? As I understand it, reasons in stubs are so you know why a post was hidden without having to unhide it.

**Comment by saxamaphone69** [comment]
>thread stubs different code

Mayhem had actually [combined Reply and Thread logic](https://github.com/ccd0/4chan-x-mayhem/commit/61510ca272569e087eb95820f49d73e70a0ea45c) around the same time as the Filter Labels.

>recreated it

Thank you.

>wrapping spans

I'll attempt a PR.

>reason for highlighting

Nah, I agree it isn't needed. I just recall one commenter wanting reasons (hiding or highlighting) as an option in the menu.

Again, thank you Tako.

**Comment by saxamaphone69** [comment]
@gir489returns 

'Filter Reason' under 'Filtering'

![image](https://github.com/user-attachments/assets/be0b13c8-42eb-4c2e-a6d5-0bafb4b98cad)
