### ISSUE TITLE
[Feature Request] Mouse hover on date too see how many hours ago a post was made

### ISSUE THREAD

**Issue by arennf57** [TuxedoTako/4chan-xt#109]
![hover mouse](https://github.com/user-attachments/assets/14cbf7cf-8e56-4406-9e31-3c6f420b7d40)

This is a feature that is enabled by default on 4chan X and I sorely miss it.

**Comment by saxamaphone69** [comment]
![image](https://github.com/user-attachments/assets/2b842817-0c51-4399-a58d-a7961ab65718)

I could be mistaken, but after enabling 'Time Formatting', head to the Advanced section and scroll to this part - should give you the option there to pick what you want on hover?
