### ISSUE TITLE
Add discernible class to HTML

### ISSUE THREAD

**Issue by saxamaphone69** [TuxedoTako/4chan-xt#11]
Would be great to be able to determine if someone is using XT or not, to specifically target them in a userstyle/userscript.

Perhaps `fourchan-xt` added to `html`? I would guess in addition to `fourchan-x` that currently gets added, just in case anyone has a catch-all for "using 4chan X".

Or, a data attribute.

**Comment by TuxedoTako** [comment]
What is your use case? Should I add the other events from https://github.com/ccd0/4chan-x/wiki/4chan-X-API too?

**Comment by saxamaphone69** [comment]
With the way [I apply my userstyle](https://github.com/saxamaphone69/ss21), I remove 4chan X's CSS. So if we look at XT's way of handling the Shortcut Icons for example, I could add a `:has()` or something to support how both X and XT do it.
I also check the `document`'s classes to determine if someone has 4chan X or OneeChan, for example. The [class name](https://github.com/TuxedoTako/4chan-xt/blob/project-XT/src/main/Main.js#L124) could be whatever you want it to be, and it would not even be used internally within 4chan XT. More if someone wanted to apply a style to 4chan X and 4chan XT separately.

I remember some people relying on some parts of the API for their own supplementary userscripts, so I'd imagine that should be carried over if it isn't already for parity's sake.

I also guess if you were to implement some of the open PR's on X, then you'd have extra features and a userstyle could add `.fourchan-xt #new-feature {}` to only affect XT.

**Comment by TuxedoTako** [comment]
> I also guess if you were to implement some of the open PR's on X, then you'd have extra features and a userstyle could add .fourchan-xt #new-feature {} to only affect XT.

I don't know if it's a good idea to keep adding classes for each feature. Is it enough for you if I just add `.fourchan-xt`, and add the version number and build date to the global `window` in case an update breaks something?

**Comment by saxamaphone69** [comment]
Oh sorry, not for each new feature. Just the one `fourchan-xt` on `html` will do. Version number isn't necessary I think.

I meant more you can target features from different versions with initial class on `html`.

Let's say 4chan XT implemented filter labels, but still used the generic `.stub` class.

I/others could, in theory, then be like
```css
.fourchan-xt .stub {
  color: green;
}
/* or use some :has() :is() :when() thing */
.fourchan-x:not(.fourchan-xt) .stub::after {
  content: 'hey did you know 4chan xt supports filter labels';
  color: red;
}
```

Which means 4chan XT gets styled as normal, and 4chan X users could see a message, or just be styled differently, due to the reuse of generic classes. My userstyle is unique in the sense it removes the CSS from 4chan X for greater control and cleaner CSS. Most OneeChan-esque users are just changing colours/fonts/some sizes.

**Comment by TuxedoTako** [comment]
Merry Christmas!

Can you try [2.3.0](https://github.com/TuxedoTako/4chan-xt/releases)? I added the `.fourchan-xt` class. I also added  `window.fourchanXT` with the version number in version and a `buildDate` `Date` object, in case I break something in a newer version. I don't have plans for future breaking changes, but you never know.
