### ISSUE TITLE
Highlighting filters stopped working

### ISSUE THREAD

**Issue by mrCr4b** [TuxedoTako/4chan-xt#112]
Since updating to version 2.15.1, my highlighting filters now are hiding threads and also posts (which is weird because I set it 'op:only;'. 
![image](https://github.com/user-attachments/assets/320e47fb-5539-41bd-b0e2-acfea94be2eb)
![image](https://github.com/user-attachments/assets/49968b5b-9829-4f2c-9534-0aa68aa501ac)
![image](https://github.com/user-attachments/assets/c2b2ceb6-889c-467a-b873-70903432be2d)

**Comment by saxamaphone69** [comment]
Are you able to post the full filters?

I used `/the/;highlight;op:only;boards:a;` in General (trying to match what you've shown) and all the threads are highlighted correctly.

![image](https://github.com/user-attachments/assets/f40903ef-162f-4ab5-a23f-9a38d2ddfda9)

**Comment by mrCr4b** [comment]
I've always put the filters at the end, like this: `boards:a;op:only;highlight;/jashin/i;`
Now I put the filters at the top and it works again: `/jashin/i;boards:a;op:only;highlight; `

**Comment by TuxedoTako** [comment]
I optimised for filters starting with the regex. I didn't know the order can be reversed. The guide doesn't specify if the options go before or after the filter, so I guess I have to support them both. I'll revert this.

**Comment by TuxedoTako** [comment]
Should be fixed in [2.15.3](https://github.com/TuxedoTako/4chan-xt/releases).
