### ISSUE TITLE
Crash on Sauce when using %hMD5

### ISSUE THREAD

**Issue by cheevos2603** [TuxedoTako/4chan-xt#115]
![image](https://github.com/user-attachments/assets/7d2a357c-19ca-4af6-b3cf-f29491b74182)
I get this crash when using 
https://nzbindex.com/search/?q=%hMD5;text:usenet;types:webm,gif
on the Sauce tab. The crash began immediately after updating to 4chan XT (userscript). The crash does not occur if I change it from %hMD5 to something else. This crash did not occur on 4chan X (chrome store install).

**Comment by TuxedoTako** [comment]
Should be fixed in [2.15.4](https://github.com/TuxedoTako/4chan-xt/releases).

**Comment by cheevos2603** [comment]
Works great, thank you
