### ISSUE TITLE
Opting for emojis as icons disallows Shortcut Text option

### ISSUE THREAD

**Issue by saxamaphone69** [TuxedoTako/4chan-xt#12]
Within the Header, there is an option to show Shortcut Icons as text instead.

With the switch to emoji icons, the accompanying text has been removed.

Not that I use that setting, but thought I'd mention it.

**Comment by TuxedoTako** [comment]
I'll fix that.

**Comment by TuxedoTako** [comment]
Fixed in [2.2.6](https://github.com/TuxedoTako/4chan-xt/releases).
