### ISSUE TITLE
Expand header detection/Force expand header

### ISSUE THREAD

**Issue by cheevos2603** [TuxedoTako/4chan-xt#120]
My header expands into multiple lines if the window size is skinny enough, but the detection for it seems to be bad. This is an issue regardless of if I am using browser text zoom or not. This issue persists if I disable OneeChan and is not caused by it. It also persists if I use shortcut icons instead of text buttons.
When using the default board list, it looks like this with a window wide enough to escape detection versus a sufficiently reduced width window:
![default board list](https://github.com/user-attachments/assets/29ab53d0-993b-4885-a9bd-6878f9dde78c)
It squeezes all the boards in when I'd much rather it just expand into multiple lines and be much more usable.

And with a custom board list (Censored because this includes a lot of catalog links to generals that I use):
![custom board list](https://github.com/user-attachments/assets/1cc4b069-88a6-45b1-86ea-84ccf4e2d542)
Rather than squeezing the text or expanding the bar, it simply pushes all the overflow offscreen.

You could consider this a bug report (fixing header window size detection?) or a feature request (add force expand header option), or both. If you make it a setting I'd suggest putting it here with other header options:
![header options](https://github.com/user-attachments/assets/54f8f473-04ba-4ed8-bf8d-080fd1128f21)

Thanks for all your work.

**Comment by TuxedoTako** [comment]
I removed the code that stopped wrapping on wide windows in [2.19.0](https://github.com/TuxedoTako/4chan-xt/releases). I hope that didn't break anything else.

**Comment by cheevos2603** [comment]
Hopefully this didn't cause problems for anyone, but it's perfect for me. Thanks.
