### ISSUE TITLE
[Feature Request] Thread Watcher: Prune Read Dead Threads and Open Unread Dead Threads

### ISSUE THREAD

**Issue by Adulau2003** [TuxedoTako/4chan-xt#122]
Currently in Thread Watcher there's functions to Open Unread Threads, and Prune Dead Threads (among others). How about one that opens JUST the Unread Dead Threads (rather than ALL Unread Threads) and one that Prunes All Read Dead Threads (rather than Prune All Dead Threads *including the ones unread*)?

**Comment by TuxedoTako** [comment]
Released in [2.17.0](https://github.com/TuxedoTako/4chan-xt/releases).

**Comment by Adulau2003** [comment]
You're amazing. Truly.
