### ISSUE TITLE
Feature Request: Warn user if their subject line has too many characters

### ISSUE THREAD

**Issue by Pentaphon** [TuxedoTako/4chan-xt#128]
4chan allows a certain character limit for the subject line and I sometimes hit it and have to have 4chan tell me to shorten it when submitting. Can 4chan-xt somehow make sure my subject line always stays within the limit instead of wasting time submitting and getting denied because it is 1 character over the limit?

**Comment by TuxedoTako** [comment]
4chan has the max_comment_chars in [a.4cdn.org/boards.json](https://a.4cdn.org/boards.json), but I don't know what the maximum is for the subject line.

**Comment by Pentaphon** [comment]
> I don't know what the maximum is for the subject line.

It's 100 characters max. I could just use a character counter but it would be handy if 4chan-xt didn't allow me to go over the limit so I don't get my post denied if I typed in 101 characters.

**Comment by TuxedoTako** [comment]
I just set `maxlength` in [2.19.0](https://github.com/TuxedoTako/4chan-xt/releases). Is that enough?

**Comment by Pentaphon** [comment]
> I just set `maxlength` in [2.19.0](https://github.com/TuxedoTako/4chan-xt/releases). Is that enough?

Yep! That's perfect. That will save me time whenever I need to post a subject line that might be too long. Thanks!
