### ISSUE TITLE
[Feature Request] WS/NWS discernible class

### ISSUE THREAD

**Issue by saxamaphone69** [TuxedoTako/4chan-xt#129]
More so for feature parity, in the native 4chan extension, a class is added to the `body` to indicate if a board is worksafe (`ws`) or not worksafe (`nws`).

I believe it's around here: https://github.com/4chenz/ChanTracking0/blob/master/javascripts/extension.js#L9353
and I do the same (poorly) in my sidedish userscript: https://github.com/saxamaphone69/ss21/blob/main/sidedish.user.js#L247

Would be nice if it was also within 4chan XT. I suppose the `ws_style` variable could be used (it's in the `<head>`), or the internal board list within 4chan X that checks if a board is nsfw. Ideally though, the ws/nws class is added to `html` like the other helper classes (`index`, `yotsuba-b`) are.

**Comment by TuxedoTako** [comment]
Added in [2.19.0](https://github.com/TuxedoTako/4chan-xt/releases).

**Comment by saxamaphone69** [comment]
Amazing as usual Tako, thank you.
