### ISSUE TITLE
Header image expansion button icon not updating on click

### ISSUE THREAD

**Issue by Katzenwerfer** [TuxedoTako/4chan-xt#13]
The button functions correctly, but the icon itself doesn't visually change upon clicking.
If icons in the header are opted out, the button keeps being an icon, but does visually update when clicked.

**Comment by TuxedoTako** [comment]
Merry Christmas!

Can you try [2.3.0](https://github.com/TuxedoTako/4chan-xt/releases)?

**Comment by Katzenwerfer** [comment]
It works like a charm, thanks!
