### ISSUE TITLE
nameBlock and capcode differences

### ISSUE THREAD

**Issue by saxamaphone69** [TuxedoTako/4chan-xt#14]
On vanilla 4chan and 4chan X, mods (and other named users) are rendered like so in a thread and on the index:
![image](https://github.com/TuxedoTako/4chan-xt/assets/877480/89d3f68b-3611-466c-87d8-9f302ccaec53)
![image](https://github.com/TuxedoTako/4chan-xt/assets/877480/5286dc65-492f-4a87-8272-f2a2c5ed8078)

4chan XT on index renders like so:
![image](https://github.com/TuxedoTako/4chan-xt/assets/877480/3435932b-5752-4563-933b-4d9ab2f4fcf6)

You'll note the `.nameBlockMod` as opposed to two separate classes `.nameBlock` and `.capcodeMod`, the lack of `.capcode` on `.name`, and the mod icon has a left over `}` in the alt tag.

Within a thread, it goes back to expected.

**Comment by TuxedoTako** [comment]
Can you try [2.3.1](https://github.com/TuxedoTako/4chan-xt/releases)?
