### ISSUE TITLE
FAQ in default header links to nowhere

### ISSUE THREAD

**Issue by saxamaphone69** [TuxedoTako/4chan-xt#15]
The default header is `[ toggle-all ]
[current-index-text:"Index"
current-catalog-text:"Catalog"
current-expired-text:"Expired"
current-archive-text:"Archive"]
[external-text:"FAQ","4chan XT"]` but the FAQ links nowhere. On 4chan X it links to `[external-text:"FAQ","https://github.com/ccd0/4chan-x/wiki/Frequently-Asked-Questions"]`

**Comment by TuxedoTako** [comment]
Can you try [2.3.1](https://github.com/TuxedoTako/4chan-xt/releases)?
