### ISSUE TITLE
Retain span within hidden thread stubs

### ISSUE THREAD

**Issue by saxamaphone69** [TuxedoTako/4chan-xt#17]
![image](https://github.com/TuxedoTako/4chan-xt/assets/877480/daf96c6e-f9be-4a1b-b9f8-a0a318256481)

Possibly due to [when Font Awesome was switched](https://github.com/TuxedoTako/4chan-xt/blob/project-XT/src/Filtering/ThreadHiding.js#L197) with Unicode icons.

In 4chan X, the `+` icon added to expand both a stubbed thread or reply was in/used a `span`.

In XT, the `+` is wrapped in a `span` for replies, but not on the index for threads.

**Comment by TuxedoTako** [comment]
Should be restored in [2.3.3](https://github.com/TuxedoTako/4chan-xt/releases).
