### ISSUE TITLE
New posts don't have IDs

### ISSUE THREAD

**Issue by octaveuranus** [TuxedoTako/4chan-xt#20]
IDs on posts which appear after initial load don't appear. Page must be refreshed for them to load. Using 4chan XT on Tampermonkey, Firefox. I can provide more info if you can't reproduce the issue. This issue does not occur for me with 4chan X v1.14.22.4.

In the image, only the first two posts were made before the page loaded initially.
![post id issue example](https://github.com/TuxedoTako/4chan-xt/assets/156021923/2af9a504-2d91-4677-acdf-e0bfd9a7d925)

**Comment by AlifianK** [comment]
Tried on Edge, violentmonkey, can be reproduced.
![image](https://github.com/TuxedoTako/4chan-xt/assets/50392169/4d116db6-8832-498f-8d61-d46c4b49352c)

**Comment by TuxedoTako** [comment]
Can you try [2.3.5](https://github.com/TuxedoTako/4chan-xt/releases)?

**Comment by AlifianK** [comment]
2.3.5 fixed that. Thanks.

**Comment by octaveuranus** [comment]
thanks boss
