### ISSUE TITLE
Viewing XT in TamperMonkey formatting issue

### ISSUE THREAD

**Issue by saxamaphone69** [TuxedoTako/4chan-xt#24]
![image](https://github.com/TuxedoTako/4chan-xt/assets/877480/6f8ccdc0-338d-4d65-8835-000d069ca774)
![image](https://github.com/TuxedoTako/4chan-xt/assets/877480/38c5f969-e10d-43fe-a421-6522915946d8)

From what I can tell this is only on TamperMonkey and everything seems okay on ViolentMonkey.

A response from the TamperMonkey issue tracker regarding someone else commenting on the 'NL' icons, not sure if it's applicable here:
>You script mixes multiple types of line endings. The start is "LF" (0x0a) only, while the rest uses "CRLF" (0x0d 0x0a).
>This change (line ending detection) was introduced to preserve existing line breaks on edit.

Doesn't actually break anything AFAIK, seems to be prevalent at the start of the script and before decaffeinate comments. Majority of the script doesn't have it.
![image](https://github.com/TuxedoTako/4chan-xt/assets/877480/7862e7e9-5dea-4367-9958-1d39c5f63eec)

**Comment by TuxedoTako** [comment]
Line endings were indeed mismatched. Should be fixed in [2.4.2](https://github.com/TuxedoTako/4chan-xt/releases).

**Comment by saxamaphone69** [comment]
Fixed in the metadata, everywhere else still present.
![image](https://github.com/TuxedoTako/4chan-xt/assets/877480/cae8f3ba-4ab1-4626-acc5-47f3c35fcbe6)
![image](https://github.com/TuxedoTako/4chan-xt/assets/877480/d75d1f59-9384-4dd4-b2d9-57f37d5d7ae0)

**Comment by TuxedoTako** [comment]
Entire file should be normalized to only use LF in [2.4.3](https://github.com/TuxedoTako/4chan-xt/releases).

**Comment by saxamaphone69** [comment]
Looks good!
