### ISSUE TITLE
Image prefetching icon incorrectly shows it is enabled by default

### ISSUE THREAD

**Issue by Katzenwerfer** [TuxedoTako/4chan-xt#26]
Wondered if prefetching was enabled by default since the icon shows as such, but when checking on the console no seemingly related queries are made unless I click the icon.

**Comment by TuxedoTako** [comment]
Will be fixed in the next release.

**Comment by TuxedoTako** [comment]
Should be fixed in [2.4.3](https://github.com/TuxedoTako/4chan-xt/releases).
