### ISSUE TITLE
Cloudflare blocked when 4chan xt is enabled

### ISSUE THREAD

**Issue by keatit71** [TuxedoTako/4chan-xt#31]
When opening 4chan it shows an error that the cloudflare domain is blocked and i need to disable this userscript to allow cloudflare to work. I found this issue on the original 4chanx github which might fix it [Link](https://github.com/ccd0/4chan-x/issues/3407).

**Comment by TuxedoTako** [comment]
For me the captcha loads, so I can't verify if the suggested change in https://github.com/ccd0/4chan-x/issues/3407 is the solution. Also the linked PR https://github.com/ccd0/4chan-x/pull/3416 mentions `object-src 'self' blob:`. Can you check if that actually solves the problem on your end?

**Comment by keatit71** [comment]
I tried the captcha again and it worked without the edit and loaded properly so not sure why it won't load and disabling this userscript allowed it to load the other times its happened

**Comment by Nate700** [comment]
It happen to me too i'm using firefox on linux

**Comment by TuxedoTako** [comment]
I'm not on linux.

**Comment by keatit71** [comment]
I'm on the 2.14.1 version of 4chan xt on windows 11 firefox with tamper monkey and this is still happening. Disabling the script then  re-enabling after 4chan has checked if the connections secure allows me to access the site but this happens every few days. 

![image](https://github.com/user-attachments/assets/af6cf128-55cf-4c45-b895-eda004a1b0e6)

**Comment by keatit71** [comment]
I've switched from tamper monkey to violent monkey to see if it was a problem with the userscript extension, i will close this with a confirmation if that was the problem.

**Comment by keatit71** [comment]
Switching to a different script extension didn't work so might be something to do with this script though i've got no idea what.

**Comment by keatit71** [comment]
latest release fixed the cloudflare issue
