### ISSUE TITLE
Add Quick(er) MD5 Filtering?

### ISSUE THREAD

**Issue by elch01** [TuxedoTako/4chan-xt#32]
Hello, can you add so that SHIFT (Or any other function button) + Click does an MD5 filter, so that you dont have to manually filter the image with a button?
From what little i understand about javascript the hide thread keyboard combination (SHIFT + Click) is handled by the "PostHiding" function and quickFilterMD5 handles the already exisiting button when manually filtering.

**Comment by TuxedoTako** [comment]
In the advanced settings, under File Info Formatting, you can add a button to the file header to add a MD5 filter. 

![msedge_gWLuYVT7VV](https://github.com/TuxedoTako/4chan-xt/assets/126348645/ad44d590-dcb9-4480-a363-056164ff9c06)

Is that enough for you? Or do you need a keyboard shortcut in combination with that click specifically?

**Comment by elch01** [comment]
Thanks for the quick response!
The latter, i keep missing the damn X button with that enabled 😄
So just for example shift-clicking the image is way easier and faster to just sort out low effort threads in the catalogue.

**Comment by TuxedoTako** [comment]
Added in [2.5.0](https://github.com/TuxedoTako/4chan-xt/releases). Can you try it?

**Comment by elch01** [comment]
Oh yeah, that works great!
![image](https://github.com/TuxedoTako/4chan-xt/assets/53192279/13297ac2-6d81-46c2-bd97-29370a7436e6)
Thank You!
