### ISSUE TITLE
'4chan Image Resizer' userscript rarely works on 4chan XT

### ISSUE THREAD

**Issue by yuk1w1fe** [TuxedoTako/4chan-xt#33]
[this script](https://greasyfork.org/en/scripts/391758-4chan-image-resizer) works fine when I use 4chanX but rarely does on 4chan XT. Nothing happens when I trigger the keybinds.

**Comment by TuxedoTako** [comment]
I'm failing to reproduce the issue. ctrl+q works for me on chrome + violentmonkey and firefox + violentmonkey. Edge eats ctrl+q for their own functionality.

What browser and user script manager are you using?

**Comment by yuk1w1fe** [comment]
Haha I figured it out. [Image Max URL](https://github.com/qsniyg/maxurl) is the problem. The addon works flawlessly but somehow the userscript causes this problem. Also, I use floorp and violentmonkey.
I'm sorry....
