### ISSUE TITLE
script often fails to update on Violentmonkey

### ISSUE THREAD

**Issue by stradus64** [TuxedoTako/4chan-xt#34]
When either trying to force an update with the "check for updates" button or when violentmonkey does it automatically the update fails often in 2 ways but sometimes it does go through correctly, not sure if it's a problem with the script packaging, VM or github.
![2024-03-04 20:34:05 screenshot](https://github.com/TuxedoTako/4chan-xt/assets/10760147/f1db51a3-8039-4bf5-a521-9000537869c9)
![2024-03-04 20:35:25 screenshot](https://github.com/TuxedoTako/4chan-xt/assets/10760147/5fdb1bd5-1a10-4f13-9324-a32f0dd9b8e9)
![2024-03-04 20:35:01 screenshot](https://github.com/TuxedoTako/4chan-xt/assets/10760147/5953bcc5-6c58-4c40-a749-470bfa748ef1)

**Comment by TuxedoTako** [comment]
Seems we're not the only ones with that problem: https://github.com/violentmonkey/violentmonkey/issues/1673. Maybe I should put the userscript on a dedicated user script site like greasyfork or something.

**Comment by AlifianK** [comment]
It always fails with the `check all for updates`. Updating the script individually always works for me though.

**Comment by TuxedoTako** [comment]
I can reproduce it, but I'm not in control on how GitHub serves release files.

**Comment by AlifianK** [comment]
Unless the script can't be updated in any way and maintaining on Greasyfork is too much of a hassle, it's not really a problem IMO.

**Comment by TuxedoTako** [comment]
I imported the script from GitHub to Greasy Fork: https://greasyfork.org/en/scripts/489508-4chan-xt. It should auto-update that version using the GitHub webhook, so it shouldn't result in future hassle.

Greasy Fork doesn't allow minified scripts, so that one will stay GitHub exclusive for the time being.
