### ISSUE TITLE
Thread Watcher: Icon's color doesn't change even though the post is replied

### ISSUE THREAD

**Issue by AlifianK** [TuxedoTako/4chan-xt#35]
![Screenshot 2024-03-06 033114](https://github.com/TuxedoTako/4chan-xt/assets/50392169/5edd8c14-e8ee-4bf8-bdf4-e67e4ea52985)
![screenshot-1709670701733](https://github.com/TuxedoTako/4chan-xt/assets/50392169/03c19611-e900-432d-966a-c4f0ba79cd67)

The thread watcher icon is usually switched to red whenever the post is quoted. Favicon is still normal.

**Comment by TuxedoTako** [comment]
Should be fixed in [2.5.2](https://github.com/TuxedoTako/4chan-xt/releases).

**Comment by AlifianK** [comment]
Thank you!
