### ISSUE TITLE
Gallery icon looks like ass on Edge.

### ISSUE THREAD

**Issue by gir489returns** [TuxedoTako/4chan-xt#37]
Seems to be a regression issue.

![image](https://github.com/TuxedoTako/4chan-xt/assets/100792176/1d4b770e-ee94-4752-b210-dfbc2114110e)

It's working fine on 4chan-x if I switch back to it.

![image](https://github.com/TuxedoTako/4chan-xt/assets/100792176/da19a48a-29ab-4497-af07-961f7ca31752)

**Comment by TuxedoTako** [comment]
I removed font awesome, because it's bloat. XT uses Unicode icons. If you know a better Unicode icon for the gallery let me know.

**Comment by gir489returns** [comment]
> I removed font awesome, because it's bloat. XT uses Unicode icons. If you know a better Unicode icon for the gallery let me know.

lmao, I thought it was the picture of the mountain and sunrise just jammed together, but it's like a mona Lisa or some shit. Word.
