### ISSUE TITLE
ThreadStats Purge Position

### ISSUE THREAD

**Issue by vampiricwulf** [TuxedoTako/4chan-xt#39]
https://github.com/ccd0/4chan-x/pull/3357
Help anons who manage General threads keep track of when they need to make the next thread.

**Comment by TuxedoTako** [comment]
Added in [2.6.0](https://github.com/TuxedoTako/4chan-xt/releases). I put it in an option under Monitoring > Thread Stats to not increase network requests for those who don't need it.
