### ISSUE TITLE
`"Image Replace" crashed on node` pop-up error

### ISSUE THREAD

**Issue by Impeta** [TuxedoTako/4chan-xt#4]
```
"Image Replace" crashed on node Post No.(x). prefetch@moz-extension://2b246608-699a-44b7-936d-918c20a8e8ad/%204chan%20XT.user.js#9:24060:11
node@moz-extension://2b246608-699a-44b7-936d-918c20a8e8ad/%204chan%20XT.user.js#9:24024:21
execute@moz-extension://2b246608-699a-44b7-936d-918c20a8e8ad/%204chan%20XT.user.js#9:366:27
fn@moz-extension://2b246608-699a-44b7-936d-918c20a8e8ad/%204chan%20XT.user.js#9:27059:13
softTask@moz-extension://2b246608-699a-44b7-936d-918c20a8e8ad/%204chan%20XT.user.js#9:27064:16
```

Comes from the Replace GIF and Replace WEBM toggles when on, within section Images and Videos.

**Comment by TuxedoTako** [comment]
Sorry for the late reply, I forgot to turn on notifications.

I tried the replace GIF and WEBM options, and I didn't get an error. Does it happen for you on a specific thread? What do you mean with "within section Images and Videos"? Can you provide a screenshot or recording and an export of your settings? If you don't have screen recording software yet I recommend [shareX](https://getsharex.com/).
