### ISSUE TITLE
feature request - hide all posts by ID

### ISSUE THREAD

**Issue by yarrmateys** [TuxedoTako/4chan-xt#41]
the script could use a way to quickly hide all posts by a selected ID on boards that support IDs. so far the only thing for those is filtering by ID, but that's not really useful since IDs change in every thread. it'd be better to click the drop menu > hide > all posts by this ID, and selecting this would collapse, or even completely remove all past and future posts by selected ID from being seen if make stub is not enabled.

**Comment by TuxedoTako** [comment]
Released in [2.7.0](https://github.com/TuxedoTako/4chan-xt/releases).

**Comment by yarrmateys** [comment]
it doesn't seem to hide future posts by the id on 2.7.1, or is that not a function?

**Comment by TuxedoTako** [comment]
I forgot.

**Comment by Tim-Veestraeten** [comment]
Should be fixed in [2.8.0](https://github.com/TuxedoTako/4chan-xt/releases).

**Comment by TuxedoTako** [comment]
Should be fixed in [2.8.0](https://github.com/TuxedoTako/4chan-xt/releases).

**Comment by yarrmateys** [comment]
there's still a slight problem with it, occassionally the option to hide all posts by ID just disappears from the menu, for all or just for some posts, as if it was on a blue board. sometimes a full refresh of the page brings it back, sometimes it doesn't.
also would be nice if it and other options in that menu could notify if they're enabled or not, like with a checkbox or something. right now you need to remember what options you marked in every thread, otherwise you press it again, unmark it and instead of hiding everything it only hides one post, or hides everything but doesn't remove the stub.

**Comment by TuxedoTako** [comment]
I think this might be a race condition between the PostHiding init and the board config loading. Usually the board config is cached, but every two hours a page load reloads the config, and doesn't use the old one before the new one is loaded. This will be fixed in the next release.

**Comment by TuxedoTako** [comment]
Race condition is fixed in [2.8.2](https://github.com/TuxedoTako/4chan-xt/releases).

> also would be nice if it and other options in that menu could notify if they're enabled or not, like with a checkbox or something. right now you need to remember what options you marked in every thread, otherwise you press it again, unmark it and instead of hiding everything it only hides one post, or hides everything but doesn't remove the stub.

What do you mean exactly? The selected options in the show menu should reflect the options you selected while hiding. Or do the check boxes not work sometimes?

**Comment by yarrmateys** [comment]
yeah, they never show up for me. i use violentmonkey on librewolf and vivaldi, could that be the reason?
edit: nevermind, it's stylechan's fault.

**Comment by TuxedoTako** [comment]
The show menu entry doesn't appear on the stubs of hidden replies, but that was already the case in 4chan X.
