### ISSUE TITLE
"Expand All Images" breaks its own icon

### ISSUE THREAD

**Issue by LeeroyGarfield** [TuxedoTako/4chan-xt#47]
Pressing "Expand All Images" icon down turns itself into text buttons.

![image](https://github.com/TuxedoTako/4chan-xt/assets/87123836/b01cd252-e970-4b23-b9c8-54c13244ee0c)

**Comment by TuxedoTako** [comment]
Fixed in [2.7.1](https://github.com/TuxedoTako/4chan-xt/releases).
