### ISSUE TITLE
"Restore from archive" menu button stopped working

### ISSUE THREAD

**Issue by stradus64** [TuxedoTako/4chan-xt#51]
> Uncaught (in promise) TypeError: this.response is null
    restore moz-extension:/// 4chan XT.user.js#89:25998
    onloadend moz-extension:/// 4chan XT.user.js#89:20836
    execTask moz-extension:/// 4chan XT.user.js#89:21058
    promise callback*VMkvw60fz8huq/$.queueTask moz-extension:/// 4chan XT.user.js#89:21063
    onloadend moz-extension:/// 4chan XT.user.js#89:20836
    onloadend moz-extension:/// 4chan XT.user.js#89:20836
    onload moz-extension:/// 4chan XT.user.js#89:20533
    HttpRequested moz-extension:///sandbox/injected-web.js:1
    onHandle moz-extension:///sandbox/injected-web.js:1
    Le moz-extension:///sandbox/injected-web.js:1

 version      2.7.1

**Comment by TuxedoTako** [comment]
Which board? /vt/? Seems archived.moe has implemented a browser check by sending a HTML page with javascript first, which 4chan XT doesn't run. You can get past the check by opening the archive manually first.

I should probably implement a better error message if something like this happens.

**Comment by stradus64** [comment]
Yes, is that archived.moe specific issue? Can it use the archive specified in settings, that's the one I mostly use manually.

![2024-04-16 19:50:38 screenshot](https://github.com/TuxedoTako/4chan-xt/assets/10760147/ff289c12-5c76-4740-bdf1-6bb8dc8d6f2f)

Also opening the exact thread in archived.moe then refreshing 4chan thread didn't help, same error.

**Comment by TuxedoTako** [comment]
I forgot to add the archive select for fetching threads when I made that feature. Should be added in [2.8.0](https://github.com/TuxedoTako/4chan-xt/releases). I also added a clearer error message.
