### ISSUE TITLE
Overlapping icons in Quick Reply

### ISSUE THREAD

**Issue by AlifianK** [TuxedoTako/4chan-xt#54]
When opening Quick Reply through this https://boards.4chan.org/vt/catalog. the icons that should be at the bottom are overlapping at the top of the box instead.
![Screenshot 2024-04-23 132851](https://github.com/TuxedoTako/4chan-xt/assets/50392169/21c7473b-c35d-4303-8b81-f9898384d443)

**Comment by TuxedoTako** [comment]
Fixed in [2.8.1](https://github.com/TuxedoTako/4chan-xt/releases).

**Comment by AlifianK** [comment]
Thanks.
