### ISSUE TITLE
File Info Formatting not working

### ISSUE THREAD

**Issue by niceguyniceguy** [TuxedoTako/4chan-xt#59]
![image](https://github.com/TuxedoTako/4chan-xt/assets/12094260/e5c0b27c-3cf2-4b33-945e-d1cfae8ec1e7)
the download button next to the filename stopped working for me about a week ago, I've tried seeing if anyone else has had this issue but I've seen no one else mention it. I tried clearing my cookies, reinstalling 4chan-xt, and the issue kept persisting.

**Comment by TuxedoTako** [comment]
Works on my machine. What browser and user script manager are you using?

**Comment by niceguyniceguy** [comment]
Brave Beta, and tamper monkey. Those are what im using.

**Comment by TuxedoTako** [comment]
I can reproduce it. I think it's a tamper monkey issue. I'll see if I can make a minimal reproduction for them.

**Comment by TuxedoTako** [comment]
Findings: does not happen on brave stable or edge dev, and also happens on Violentmonkey, so I suspect an issue on Brave's side. I opened bug issues for both: https://github.com/Tampermonkey/tampermonkey/issues/2056, https://github.com/violentmonkey/violentmonkey/issues/2098

**Comment by niceguyniceguy** [comment]
ahh nvm, it was the extension PngExtraEmbedder doing all the troublemaking.

**Comment by TuxedoTako** [comment]
>it was the extension PngExtraEmbedder doing all the troublemaking.

I didn't have this extension when I reproduced the issue and reported it to Tampermonkey and Violentmonkey. This issue was also confirmed on Brave's side: https://github.com/brave/brave-browser/issues/38256.
