### ISSUE TITLE
Embedding dialog saves the entire style attribute value in the storage instead of just the X/Y coordinates

### ISSUE THREAD

**Issue by Hash6232** [TuxedoTako/4chan-xt#62]
Probably unintentional but if you manually edit the CSS of the embedded dialog and then have 4chanXT save its position (by closing or moving the dialog I guess), the script is going to save the entire style in the storage along with any inline property you might have temporarily added to the node.

![image](https://github.com/TuxedoTako/4chan-xt/assets/164906916/4bc0f9b6-1de1-4ced-9623-60dcb6fb643f)

**Comment by TuxedoTako** [comment]
I don't know if that's intentional, [that behaviour is over 10 years old](https://github.com/ccd0/4chan-x/commit/b3d7f30f3aff07f93ca35acaafabe36fd0e65263#diff-0873a31ae12ae07319c55bf30e49b458370da25212cc937f3f690e340dea7c8dR83). I'll change that. Don't know when.
