### ISSUE TITLE
spin class animation wobbles

### ISSUE THREAD

**Issue by saxamaphone69** [TuxedoTako/4chan-xt#64]
Because the refresh icon is slightly rectangular, it doesn't spin in a full circle/on axis.

https://github.com/TuxedoTako/4chan-xt/assets/877480/a114caa3-8157-4c77-b5e2-2629da1e6a01

Adding `height: 14px` and `width: 14px` to the anchor, fixes it

https://github.com/TuxedoTako/4chan-xt/assets/877480/6dc407b2-7d59-4e05-b25b-419899af009d

Though I don't think just adding those 2 properties to `.spin` is a proper fix, more a band-aid solution.

**Comment by TuxedoTako** [comment]
If you're that bothered by it, I recommend [transform-origin](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-origin), messing with the width and height is more likely to break the layout.
