### ISSUE TITLE
Sanitizing button for the json

### ISSUE THREAD

**Issue by Janaue** [TuxedoTako/4chan-xt#69]
with the original 4chanX, i wanted to clean the .json from personal history before exporting the settings
https://github.com/ccd0/4chan-x/issues/2546
but it was never implemented.

Is it possible to create at the top of the setting window a button like the button counting the ''hidden threads'', when the button is clicked all the personal history of the user is cleared.

**Comment by TuxedoTako** [comment]
[2.15.0](https://github.com/TuxedoTako/4chan-xt/releases) adds an option to export without history.
