### ISSUE TITLE
Posts you've made not being remembered?

### ISSUE THREAD

**Issue by Revemohl** [TuxedoTako/4chan-xt#7]
I just decided to try XT today, and one thing I've noticed is how none of my own posts are still marked as being mine on page reload. Toggling the (You) manually on the dropdown menu works, but that's about it.
I'm using Firefox ESR 115 with Tampermonkey 4.19, and 4chan-xt 2.1.3.

**Comment by TuxedoTako** [comment]
Can you test [2.1.4](https://github.com/TuxedoTako/4chan-xt/releases/tag/XT2.1.4)?

**Comment by Revemohl** [comment]
> Can you test [2.1.4](https://github.com/TuxedoTako/4chan-xt/releases/tag/XT2.1.4)?

I just updated and made a few quick posts to check, everything seems to be working fine after refresh.
