### ISSUE TITLE
Dead quotes from another board don't link properly

### ISSUE THREAD

**Issue by anonymousmaggot** [TuxedoTako/4chan-xt#70]
If there's a quote going to a dead post on another board, 4chanXT gets confused and thinks the quote is coming from a post in the current thread. The hover/inline preview correctly gets the right post from the archive (most of the time), but middle clicking on the quote link opens the current thread in the archive, trying to locate a non-existent post.
For example:
https://boards.4chan.org/vip/thread/125258#p127672
When hovering or clicking on >>>/mlp/1 here, it shows moot's post. But the quote *actually* links to https://boards.4chan.org/vip/thread/125258#p1. Sometimes after showing the correct post it will even forget the post that was retrieved from the archive, and instead display "Post not found."
I know this is a rather niche issue but it crops up a lot in the 4chan Happenings Thread, where posts from all over the site are linked, many of which get deleted. With 4chanX I could click my scroll wheel to open a dead thread in a new tab, but now I have to click to embed it, then middle-click the "No." in the embedded post.

**Comment by TuxedoTako** [comment]
Should be fixed in [2.10.2](https://github.com/TuxedoTako/4chan-xt/releases).

**Comment by anonymousmaggot** [comment]
Thanks!
