### ISSUE TITLE
[Suggestion] Convert images to <4MB (or board's limit equivalent) automatically if size above limit

### ISSUE THREAD

**Issue by assignmentchampionship** [TuxedoTako/4chan-xt#72]
4chan's archaic image limitations make it annoying to deal with, finding an alternative image often means you have to pick between an image either way too big or way too small for viewing pleasure. If this isn't the place for suggestions then feel free to close this ticket.

**Comment by TuxedoTako** [comment]
Suggestions are welcome. That doesn't automatically mean I spend my free time on them.

**Comment by TuxedoTako** [comment]
Can you try [2.11.0](https://github.com/TuxedoTako/4chan-xt/releases)?

**Comment by saxamaphone69** [comment]
@TuxedoTako Is there a way to get the converted file to be just under the max file size? For example on /g/, a 5MB image would get compressed to 3.9MB, as opposed to a 1.3MB image?

**Comment by TuxedoTako** [comment]
I'm just using the build in [canvas to blob](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas/convertToBlob) functions, starting with a jpeg with a quality of 90%, and going lower in steps of 10% until it fits. There aren't any advanced options. If you want advanced functions, I used [squoosh.app](https://squoosh.app) before. I'm not planning on adding advanced image editor software to 4chan XT. This is just a quick and easy way to not have to worry about manually converting images until they fit.

**Comment by talizea** [comment]
> I'm just using the build in [canvas to blob](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas/convertToBlob) functions, starting with a jpeg with a quality of 90%, and going lower in steps of 10% until it fits. There aren't any advanced options. If you want advanced functions, I used [squoosh.app](https://squoosh.app) before. I'm not planning on adding advanced image editor software to 4chan XT. This is just a quick and easy way to not have to worry about manually converting images until they fit.

thanks, very cool, generally it works just fine
there's a slight edge case in the file size calculation though (binary decimal related I guess), so 3.92MB images exceed the "4MB" limit
4194304 decimal bytes, 4 binary MB according to https://a.4cdn.org/boards.json

**Comment by TuxedoTako** [comment]
> there's a slight edge case in the file size calculation though (binary decimal related I guess), so 3.92MB images exceed the "4MB" limit

Where are you getting this? The comparison is done in bytes. I just tested with a file between 4 000 000 and 4 194 304 bytes, and it didn't get auto converted. 

https://github.com/TuxedoTako/4chan-xt/blob/be6280ecc7765b60c954c0d107026136ab71f485/src/Posting/QR.ts#L2118

![msedge_v279oCt1MQ](https://github.com/user-attachments/assets/d1f29e2f-2032-4cc5-9104-e9757e7a92e5) ![msedge_qT6CreXh1a](https://github.com/user-attachments/assets/654bd4a8-b841-4e3f-8972-26e0cf1fec2c)

**Comment by talizea** [comment]
https://cdn-storage-media.tass.ru/tass_media/2024/11/13/8/1731488895222707_8p-61gMu.jpg

6608kb (6.45mb)

>Image was too large (6.45 MB) and got converted to jpg (3.92 MB). It might have lost transparency or animation.

>Error: File too large.

**Comment by TuxedoTako** [comment]
Weird, the browser detects it as below the max file size. 

![msedge_BU9SfZZ28O](https://github.com/user-attachments/assets/4886363f-0487-4f2d-9756-2a58e6d5c73d)

Almost 80 kB of margin, so I don't know why the server would reject it. I must admit I just logged the data to be submitted, but didn't actually submit it, since I don't know where to just spam test images.
