### ISSUE TITLE
bug: selected image to upload only showing a preview in quick reply window in 1 out of 3 cases (and after)

### ISSUE THREAD

**Issue by stradus64** [TuxedoTako/4chan-xt#75]
there seem to be 3 ways to select image to add to post

1. ctrl+v to paste image from clipboard (obtained via right click on any image -> Copy Image)
2. entering direct image link (chain icon)
3. system file picker

Method 2 and 3 doesn't show image preview. Method 1 does. After selecting an image using method 1, method 2 and 3 will also start showing the preview. 2 and 3 seems to be missing some preview activation code that 1 has.

![2024-07-13 22:30:57 screenshot](https://github.com/user-attachments/assets/50e1973a-1c85-45a3-8ce5-af62b35281ca)

**Comment by saxamaphone69** [comment]
![image](https://github.com/user-attachments/assets/3e1c2d3f-94ad-41f4-9a14-32d7a093a0b4)

All 3 methods work on my machine.

What OS, browser, and userscript manager are you using?

**Comment by stradus64** [comment]
Arch Linux, Firefox, Violentmonkey
All 3 methods work for me too but only after priming with 1, if I refresh page 2 and 3 stops working, then work again after using 1 again if I wasn't clear

**Comment by stradus64** [comment]
Looking more into it the preview is a part of "Dump list" functionality, besides pasting from clipboard it can be opened by clicking the plus icon at the bottom of QR window
`() => nodes.el.classList.toggle('dump')`
Still, would be useful if the file picker and url import method also enabled it to get the image preview

**Comment by TuxedoTako** [comment]
Can you try [2.11.0](https://github.com/TuxedoTako/4chan-xt/releases)?

**Comment by stradus64** [comment]
2.11.0 fixed this
