### ISSUE TITLE
Does the sound player support autoplaying while hovering over the image, rather than expanding?

### ISSUE THREAD

**Issue by Tenome** [TuxedoTako/4chan-xt#79]
I only just now installed XT, so I'm not entirely familiar with it. The original sound player supported playing while hovering with 4chan X, but it doesn't seem to work in XT. I have the original sound player off. The sound plays if I expand the image, but not when I hover expand over it.

Firefox, Violentmonkey, XT 2.11.1.

**Comment by TuxedoTako** [comment]
No, the build in sound player is a lot simpler than the full one.

You can disable the build in one, and use the patched full sound player linked in https://github.com/TuxedoTako/4chan-xt/issues/36#issuecomment-1987186336, where I also explain why it needed to be patched.

**Comment by Tenome** [comment]
Ah, no worries. Thanks.
