### ISSUE TITLE
Integrate GhostPostMixer into your userscript?

### ISSUE THREAD

**Issue by Impeta** [TuxedoTako/4chan-xt#8]
https://git.coom.tech/tutel/4chan-ghostpostmixer

In essence, it scrapes then puts in back in place formerly deleted posts that hasn't been replied by anyone. This one is Javascript just like yours, so hopefully it should be seamless to integrate, and maybe then polish it up some more (currently it doesn't put back in uploaded images off a post)? Thanks in advance!

**Comment by TuxedoTako** [comment]
You're lucky I had some extra free time. You can try [2.2.0](https://github.com/TuxedoTako/4chan-xt/releases/tag/XT2.2.0). It's not really an integration of GhostPostMixer, but a replication of it's functionality using what was already in 4chan X(T). There was already functionality to parse archive posts for the preview when hovering of a post number of a deleted post. I was able to use that. 

To not send to much traffic to the archives, this action has to be manually triggered. It's in the drop down menu on the top right. [/v/655403956](https://boards.4channel.org/v/thread/655403956) has it's 7th post deleted, so you can test there.

**Comment by Impeta** [comment]
Wow, I begged for a crumb and you had gone overboard and lent me few breads! This is much better, even resolving the issue of images from archives not being brought up over along deleted posts. Per my successful testings, this renders moot the GhostPostMixer thingy. Thanks! Tested it on both 4channel and 4chan, either working like a charm. 😄

I see though that it's only manually enabled. Would it be feasible if you made it into a checkmark? Obviously, by default, you should leave it opt-out, only then to be opt-in back manually by us. Hopefully that's not asking much, but I'm either way very happy with the delivered function. Thanks, once again! 👍

**Comment by TuxedoTako** [comment]
What's stopping you from opening a PR yourself?

**Comment by Impeta** [comment]
Oh, I don't code, sadly... I'm really content still with this implementation, though I don't know anything programming. The minimum I can do is reporting bugs back or feature requesting.

**Comment by TuxedoTako** [comment]
A legacy codebase converted from an other language is probably not the best place to start either. I do web dev as my job, and I still don't understand this code base completely. But since any development I do on this is done in my free time, I honestly just do what I feel like doing. I implemented fetching deleted posts because I'm often interested in those myself.

**Comment by TuxedoTako** [comment]
Speaking of not understanding the code, I broke scrolling to the last read post with 2.2.0. I fixed that in [2.2.1](https://github.com/TuxedoTako/4chan-xt/releases). I also restored automatic updates, which are now pointed to the GitHub releases. So this should be the last time you have to update manually.

**Comment by ilcane87** [comment]
Doesn't seem to work on chrome extension:

```
Access to XMLHttpRequest at 'https://archived.moe/_/api/chan/thread/?board=u&num=4204262' from origin 'https://boards.4chan.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
script.js:1636 4chan XT failed to load: https://archived.moe/_/api/chan/thread/?board=u&num=4204262
(anonymous) @ script.js:1636
error (async)
$.on @ script.js:1820
(anonymous) @ script.js:1635
ajax @ script.js:18102
restore @ script.js:24951
(anonymous) @ script.js:25002
Show 6 more frames
Show less
script.js:24964 Uncaught TypeError: Cannot read properties of null (reading '4204262')
    at XMLHttpRequest.onloadend (script.js:24964:47)
onloadend @ script.js:24964
XMLHttpRequest.send (async)
(anonymous) @ script.js:1638
ajax @ script.js:18102
restore @ script.js:24951
(anonymous) @ script.js:25002
Show 5 more frames
Show less
script.js:1638 
        
        
       GET https://archived.moe/_/api/chan/thread/?board=u&num=4204262 net::ERR_FAILED 403 (Forbidden)
```

**Comment by TuxedoTako** [comment]
I think this is the same issue as https://github.com/TuxedoTako/4chan-xt/issues/51. If the archive blocks cross origin requests, I don't think I can fix that on the script side.

**Comment by ilcane87** [comment]
> I think this is the same issue as #51. If the archive blocks cross origin requests, I don't think I can fix that on the script side.

What's strange is that dead posts and threads are correctly loaded when I hover a reference to them, I thought "Restore from archive" used the same type of requests to the archive website.

**Comment by TuxedoTako** [comment]
There is a difference in the extension version: the human readable error message I added wasn't shown. This will be fixed in the next release.
But it looks like both archive.moe and archive of sins block cross origin requests for a full thread.
