### ISSUE TITLE
"Thread Hiding Buttons" initialization crashed

### ISSUE THREAD

**Issue by CharAznableLoNZ** [TuxedoTako/4chan-xt#80]
"Thread Hiding Buttons" initialization crashed.
QuotaExceededError: The quota has been exceeded.
(4chan XT TuxedoTako v2.11.1 userscript on gecko at 13225,13207,25857,22195,25763,1734,25742,2232,25741,26466,1584)

Hiding multiple threads on a board causes thread hiding buttons to not load and hidden threads to be displayed again.  The only way to fix it is to use the unhide all threads button.  4chan-x also has this problem.

**Comment by TuxedoTako** [comment]
Can you try increasing dom.storage.default_quota in about:config as described in <https://support.mozilla.org/en-US/questions/1353337>?

**Comment by CharAznableLoNZ** [comment]
So far that seem to fix it.
