### ISSUE TITLE
[Bug] "Download file with original filename" breaks on encoded Sound URLs. on Firefox

### ISSUE THREAD

**Issue by Tenome** [TuxedoTako/4chan-xt#81]
[Example](https://boards.4chan.org/v/thread/683678952#p683683129)

Downloads as: `average stranger of paradise enjoyer [sound=https_3A_2F_2Ffiles.catbox.moe_2Fe547nk.mp3].png`
Supposed to be: `average stranger of paradise enjoyer [sound=https%3A%2F%2Ffiles.catbox.moe%2Fe547nk.mp3].png`

ViolentMonkey 2.2.0
Firefox Dev 129.0b8 (64-bit)
XT 2.11.1 

After some testing, 126.0b9 is the last verion of Firefox that didn't mess up the encoded URL filenames. 127.0 changed it. Any idea which setting this might be?

Chrome works as intended.

**Comment by TuxedoTako** [comment]
This is intended on firefox' side, and can't be worked around: https://support.mozilla.org/bm/questions/1439267.

**Comment by Tenome** [comment]
Lame, yeah I also got a similar reply when I asked on their forum. Oh well, guess I'll just downgrade or rename the files myself. Thanks.
