### ISSUE TITLE
Backspacing doesn't reload captcha anymore

### ISSUE THREAD

**Issue by yuriks** [TuxedoTako/4chan-xt#85]
It used to be in 4chan X that if you pressed backspace on the empty captcha field, it would trigger a captcha reload. I'm not sure if it was intentionally removed or not, but the same thing does not work in XT as of 2.12.0.

Exacerbating this, there's an issue with tab ordering in the form, where if you press Shift-Tab while at the captcha input field to move focus to the captcha reload button, press space, and then Tab again, it will instead move focus to the "Files" button instead of back to the field, which you need to Shift-Tab once again to go back to.

I use Tampermonkey on Firefox 128, running on Windows 10.

**Comment by TuxedoTako** [comment]
The captcha is handled by 4chan's own script.

**Comment by yuriks** [comment]
Yeah, I tried it out and it seems it stopped working on 4chan X too. Looks like it was just a case of bad timing of this change happening exactly when I switched scripts. Apologies for the false report.
