### ISSUE TITLE
Sound posts with short audio won't loop audio

### ISSUE THREAD

**Issue by Hash6232** [TuxedoTako/4chan-xt#89]
I tried playing webm sound posts and the audio loops correctly along with the webm but when I try to do the same with a gif the audio will stop playing after the first time. Here's a short sample audio `[sound=files.catbox.moe%2F8suuzd.ogg]`.

And here's a gif in case you need something to test it with:

![sip 01](https://github.com/user-attachments/assets/0ce0a3be-ab1e-4d8c-ac0c-d895fe206cd2)

**Comment by TuxedoTako** [comment]
Should be fixed in [2.13.2](https://github.com/TuxedoTako/4chan-xt/releases).

**Comment by Hash6232** [comment]
Works on my end. Thank you
