### ISSUE TITLE
"Force Noscript Captcha" option causes error

### ISSUE THREAD

**Issue by talizea** [TuxedoTako/4chan-xt#9]
> "Captcha Configuration" initialization crashed. [[report](https://github.com/TuxedoTako/4chan-xt/issues)]
> TypeError: Cannot read properties of undefined (reading 'noscript')
> (4chan XT TuxedoTako vXT 2.2.2 userscript on blink at 1881,26832,22642,26735,21280,26714,21969,26709,27444,20998)

Violentmonkey 2.16 on Edge/Chromium 119

that being said, no idea if that option is still relevant to begin with at all (I don't see any difference in captchas whether it's on or off?)

also using the [Joshi Koukousei Captcha Service](https://git.coom.tech/araragi/JKCS/) extension

**Comment by TuxedoTako** [comment]
Thanks for reporting this. This was an error made when migrating from CoffeeScript on a feature I don't use, and I don't think it matters on 4chan. But 4chan X(T) has a long list of different image board websites, so it might be used elsewhere. I created [2.2.3](https://github.com/TuxedoTako/4chan-xt/releases/tag/XT2.2.3) for the fix.
