### ISSUE TITLE
"You have to wait a while before doing this again"

### ISSUE THREAD

**Issue by CharAznableLoNZ** [TuxedoTako/4chan-xt#92]
This pops up on an orange banner and a notification any time I open new threads.  Not post or make new threads, just open them.  What is it and how do I disable it?

**Comment by TuxedoTako** [comment]
I couldn't find that error in the XT code base. I suspect it's a message propagated by the quick reply. Do you have both the "Persistent QR" and "Auto-load captcha" settings enabled? Cloudflare might be complaining about too many captcha requests, but I'm not sure.

**Comment by yourmom-420** [comment]
disable auto load captcha to fix it

**Comment by CharAznableLoNZ** [comment]
I think it may be a notification generated by 4chins itself, I was getting double notifications today after opening a few threads.  I'll disable captcha auto load.  I've noticed the captcha solver script I use is having trouble and am wondering if it's related.
