### ISSUE TITLE
Editing an image in Tegaki still results in "Duplicate file" error

### ISSUE THREAD

**Issue by Haldeyr** [TuxedoTako/4chan-xt#93]
Editing a picture in Tegaki to bypass the duplicate file filter isn't working, even after drawing over the image

**Comment by TuxedoTako** [comment]
Whoops, I broke Tegaki integration in the last version. That will be fixed in the next one.

**Comment by TuxedoTako** [comment]
Should be fixed in [2.13.1](https://github.com/TuxedoTako/4chan-xt/releases).

**Comment by Haldeyr** [comment]
Working perfectly now, thank you for all of your hard work <3
