### ISSUE TITLE
[Feature request] Improve signal:noise ratio by silencing persistent & habitual spammers

### ISSUE THREAD

**Issue by OnlyFanon** [TuxedoTako/4chan-xt#94]
Hi. I'm very often on high-traffic generals on /pol/ that are visited by bot-like trolls who drop the same images or say the same things over and over again. Filter by unique id catches them but they just show up next bread. Some of them have persisted for years and paste the same gore / scat / lines on bread after bread.
Could we have a feature where (a regex | an image MD5) automatically blocks not just that post, but that Unique ID for the thread? Would be a great measure against bot-like trolls.
Once they figure out this is happening, yeah they could get over it by fuzzing the text or generating a new image with a hash but that would significantly increase their workload and it'd mean that if they wanted to post the same scat images at least they may have had to look at it themselves.

**Comment by TuxedoTako** [comment]
[2.15.0](https://github.com/TuxedoTako/4chan-xt/releases) adds a new filter option that hides all posts from a poster if a filter is hit.

**Comment by TuxedoTako** [comment]
2.15.1 fixes that filter not applying to new posts.

**Comment by OnlyFanon** [comment]
Champ, thank you so much for this feature. Could you tell me where I can find it? 
![4chanXT-filter](https://github.com/user-attachments/assets/39348cd3-fa82-4166-ac82-edb39bdc8ec6)

I couldn't find it here and I looked and looked everywhere I could think of. Not there, not in the advanced options, not when filtering a comment.

**Comment by TuxedoTako** [comment]
You enable it per filter with the `;poster` option.

**Comment by OnlyFanon** [comment]
What a legend, thank you sir.
