### ISSUE TITLE
ThreadExpansion no longer works

### ISSUE THREAD

**Issue by saxamaphone69** [TuxedoTako/4chan-xt#97]
Just transferring [my comment](https://github.com/TuxedoTako/4chan-xt/issues/71#issuecomment-2268573818) from #71 to here, as a separate issue.

**Comment by TuxedoTako** [comment]
Should be fixed in [2.13.2](https://github.com/TuxedoTako/4chan-xt/releases).

**Comment by saxamaphone69** [comment]
Posts are being added as children within the OP post, rather than as children of the thread.

It's also missing the extra bottom summary that was added so you could contract the expanded thread.

**Comment by TuxedoTako** [comment]
Can you try [2.13.3](https://github.com/TuxedoTako/4chan-xt/releases)?

**Comment by saxamaphone69** [comment]
I think that's done it! Thank you!
