### ISSUE TITLE
Dead posts restored from arch.b4k.co have wrong image URLs

### ISSUE THREAD

**Issue by vertc** [TuxedoTako/4chan-xt#99]
1. enable `Resurrect Quotes: Link dead quotes to the archives, and support inlining/previewing of archive links like quote links.`
2. go to any thread on /v/ or /vg/ and ctrl+f for (Dead) posts that have an image attached.
3. the restored post has a working thumbnail, but the full image URL seems to be wrong.

example on a random currently alive thread [>>>/v/686955215](https://boards.4chan.org/v/thread/686930440#686955215):
* restored image URL (wrong): https://arch.b4k.co/v/full_image/1724808851.jpg
* actual URL in the archive: https://arch-img.b4k.co/v/1724808851773.jpg (nsfw)

![image](https://github.com/user-attachments/assets/c98cbcfe-fc6b-48e7-8f88-62e22e693802)

seems that `/full_image/` is not needed and the last 3 numbers are missing. i'm not sure if it affects all images.
tested on clear userscript install on firefox

**Comment by TuxedoTako** [comment]
I think the code for https://github.com/TuxedoTako/4chan-xt/issues/77 is mistakenly applied here.

**Comment by TuxedoTako** [comment]
Should be fixed in [2.13.2](https://github.com/TuxedoTako/4chan-xt/releases).

**Comment by vertc** [comment]
confirmed it works.
thanks!
